---
# for newivrservers
# cti copy part
- name: cti copy newivrservers/bin file
  copy: src={{item}} dest={{cti_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ['newivrservers/*']
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['cti', 'cti_bin', 'cti_ivr_bin', 'cti_newivr_bin']
  notify: ['restart cti']

- name: cti copy newivrservers/conf file
  copy: src={{item}} dest={{cti_conf_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/conf/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['cti', 'cti_conf', 'cti_ivr_conf', 'cti_newivr_conf']
  notify: ['restart cti']

# cti template part
- name: cti template newivrservers/conf
  template: src={{item}} dest={{cti_conf_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/conf/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['cti', 'cti_temp_conf', 'cti_ivr_temp_conf', 'cti_newivr_temp_conf']
  notify: ['restart cti']

