---
# for newivrservers
# pbx copy part
- name: copy newivrservers/bin file
  copy: src={{item}} dest={{pbx_bin_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ['newivrservers/bin/*']
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_bin', 'pbx_ivr_bin', 'pbx_newivr_bin']
  notify: ['restart pbx']

- name: copy newivrservers/etc file
  copy: src={{item}} dest={{pbx_etc_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/etc/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_etc', 'pbx_ivr_etc', 'pbx_newivr_etc']
  notify: ['restart pbx']

- name: copy newivrservers/mod file
  copy: src={{item}} dest={{pbx_modules_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/modules/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_mod', 'pbx_ivr_mod', 'pbx_newivr_mod']
  notify: ['restart pbx']

- name: copy newivrservers custom sounds
  copy: src={{item}} dest={{pbx_custom_sounds}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/sounds/custom/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_sounds','pbx_ivr_sounds', 'pbx_newivr_sounds', 'pbx_newivr_custom_sounds']
  notify: ['restart pbx']

- name: copy newivrservers ytotts sounds
  copy: src={{item}} dest={{pbx_ytotts_sounds}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/sounds/ytotts/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_sounds', 'pbx_ivr_sounds', 'pbx_newivr_sounds', 'pbx_newivr_ytotts_sounds']
  notify: ['restart pbx']

- name: copy newivrservers jishida sounds
  copy: src={{item}} dest={{pbx_jishida_sounds}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/sounds/jishida/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_sounds', 'pbx_ivr_sounds', 'pbx_newivr_sounds', 'pbx_newivr_jishida_sounds']
  notify: ['restart pbx']

# pbx template part
- name: template newivrservers/etc
  template: src={{item}} dest={{pbx_etc_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["/etc/ansible/roles/pbx/files/newivrservers/etc/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_temp_etc', 'pbx_ivr_temp_etc', 'pbx_newivr_temp_etc']
  notify: ['reload pbx']
