- name: copy newivrservers custom sounds
  copy: src={{item}} dest={{pbx_custom_sounds}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/sounds/custom/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_sounds','pbx_ivr_sounds', 'pbx_newivr_sounds', 'pbx_newivr_custom_sounds']
  notify: ['restart pbx']

