- name: copy newivrservers jishida sounds
  copy: src={{item}} dest={{pbx_jishida_sounds}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["newivrservers/sounds/jishida/*"]
  when: ansible_eth0.ipv4.address in groups['newivrservers']
  tags: ['pbx', 'pbx_sounds', 'pbx_ivr_sounds', 'pbx_newivr_sounds', 'pbx_newivr_jishida_sounds']
  notify: ['restart pbx']

