- name: template oldivrservers/etc
  template: src={{item}} dest={{pbx_etc_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["/etc/ansible/roles/pbx/files/oldivrservers/etc/*"]
  when: ansible_eth0.ipv4.address in groups['oldivrservers']
  tags: ['pbx', 'pbx_temp_etc', 'pbx_ivr_temp_etc', 'pbx_oldivr_temp_etc']
  notify: ['reload pbx']

