---
- include: 12.yaml from_main_tag={{from_role_tag}}
  when: from_role_tag=="111,222"
- include: 1.yaml from_main_tag={{from_role_tag}}
  when: from_role_tag=="111"
#- name: make directory for test.
#  raw: mkdir -p /tmp{{pbx_path}} /tmp{{cti_path}} /tmp{{html_path}}
#- name: mv template
#  template: src=sip_additional.conf dest=/tmp/data/justcall/pbx/sip_additional.conf mode='preserve'
#  when: 222==222
#- name: write some vriables
#  raw: echo {{ansible_eth0.ipv4.address}} > /tmp/data/justcall/pbx/sip_additional.conf
#- name: mv template
#  template: src=extension_additional.conf dest=/tmp/data/justcall/pbx/etc/extension_additional.conf mode='preserve'
#- name: copy file
#  copy: 
#- name: cp get_license.sh
#  template: src='get_license.sh' dest={{script_path}}/get_license.sh mode=preserve

#- name: copy file
#  copy: src=192.168.18.33/etc/httpd/conf/httpd.conf dest=/etc/httpd/conf/httpd.conf force=yes
#  notify:
#    - restart httpd
#  tags: httpd

#- template: src=testfile dest=/tmp{{pbx_path}}/testfile
#  tags: mytest
