---
# for assignservers
# crond copy part
- name: crond copy assignservers/justcall file
  copy: src={{item}} dest={{crond_justcall_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ['assignservers/justcall/']
  when: ansible_eth0.ipv4.address in groups['assignservers']
  tags: ['crond', 'crond_justcall', 'crond_ivr_justcall', 'crond_assign_justcall']
  notify: ['restart crond']

- name: crond copy assignservers/public file
  copy: src={{item}} dest={{crond_public_path}} backup=yes owner=justswitch group=justswitch mode=0755
  with_fileglob: ["assignservers/public/*"]
  when: ansible_eth0.ipv4.address in groups['assignservers']
  tags: ['crond', 'crond_public', 'crond_ivr_public', 'crond_assign_public']
  notify: ['restart crond']
